FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTest

FROM openjdk:17.0.11-jdk-slim
COPY --from=build /targe/simulateur_aerien-0.0.1-SNAPSHOT.jar demo.jar
EXPOSE 8080
ENTRYPOINT["java","-jar","demo.jar"]

