version: '3.8'

services:
  database:
    image: mysql:8
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Simulateur_aerian
    ports:
      - "3308:3306"  # Expose le port MySQL à l'extérieur

  backend:
    image: simulateur_aerien-backend:latest  # Utilise l'image Docker déjà construite de ton backend
    container_name: my_spring_app
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/Simulateur_aerian?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8084:8084"  # Mappe le port 8084 du conteneur à l'extérieur
